collections:
  portfolio:
    output: true
  services:
defaults:
  -
    portfolio:
      path: ""
      type: "portfolio"
    values:
      image_path: /img/
      category: 
      project_name: 
      link: http://

plugins:
 - jekyll-admin